### ISSUE TITLE
The tag 'script' is disallowed except in specific forms.

### ISSUE THREAD

**Issue by theod07** [dfrankland/ampreact#3]
Hi,
I cloned the repo and ran the npm server with `npm start`.
When I loaded the source html into the AMP validator (https://validator.ampproject.org/) I see that it fails with error message **The tag 'script' is disallowed except in specific forms.**

Specifically, it's a <script> tag that shows up inside of `<body>`. Seems like this <script> tag wraps around all of the body content. Do you know how we can resolve this?

Thanks in advance!

PS I got the source html by going to `view-source:localhost:3001`

**Comment by imparvez** [comment]
@dfrankland the same issue which I'm stuck on, Can you help us on this?

**Comment by dfrankland** [comment]
Hello! This was previously validating, but I think several things have changed since AMP HTML was first released.

I've recently gone through and completely updated `ampreact` with even more modern tools for building an AMP HTML app. Please, re-clone this repo and try it out! I am sure that you'll be happy with the new tools at your disposal :+1:
